Fix implicit function declarations
error: implicit declaration of function 'panic' is invalid in C99

panic is the old name of this function. Its new name is Tcl_Panic. tcl.h
defines a compatibility macro but not on macOS because of an alleged
conflict with mach/mach.h.

Imported from https://github.com/macports/macports-ports/commit/6593d3f03168bb983688cbf1076b5a7d305a2345
Path: https://github.com/macports/macports-ports/blob/master/x11/tktable/files/panic.patch